In [1]:
import numpy as np

In [2]:
# Outros formas de manipulaçao de arrays

print("Numeros inteiros aleatorios")

int_numbers = np.random.randint(1, 200, size=50)
int_numbers

Numeros inteiros aleatorios


array([ 37, 148, 174, 109, 175, 122,  39,  54, 184,  96,  74, 145,  20,
        95, 185, 121,  34,  43, 189, 191,  44,  51,  73,  55, 124,  12,
       142, 100, 191,  16, 194,  33,  64,  11,  60, 195,  55, 170, 176,
        92,   6, 125, 164,   7,  15, 104,  94,  89, 191, 121])

In [3]:
# Ordenado um array

int_numbers.sort()

int_numbers

array([  6,   7,  11,  12,  15,  16,  20,  33,  34,  37,  39,  43,  44,
        51,  54,  55,  55,  60,  64,  73,  74,  89,  92,  94,  95,  96,
       100, 104, 109, 121, 121, 122, 124, 125, 142, 145, 148, 164, 170,
       174, 175, 176, 184, 185, 189, 191, 191, 191, 194, 195])

In [4]:
# Selecionando elementos de um array com base no indice

# Primeiros 10 elementos

int_numbers[:10]


array([ 6,  7, 11, 12, 15, 16, 20, 33, 34, 37])

In [5]:
# Tudo o que vem depois dos 15 primeiros elementos

int_numbers[15:]

array([ 55,  55,  60,  64,  73,  74,  89,  92,  94,  95,  96, 100, 104,
       109, 121, 121, 122, 124, 125, 142, 145, 148, 164, 170, 174, 175,
       176, 184, 185, 189, 191, 191, 191, 194, 195])

In [6]:
int_numbers[15:20]

array([55, 55, 60, 64, 73])

In [7]:
# Selecionando os elementos de 2 em 2

int_numbers[::4]

array([  6,  15,  34,  44,  55,  74,  95, 109, 124, 148, 175, 189, 194])

In [8]:
# Sort decrescente

int_numbers[::-1]

array([195, 194, 191, 191, 191, 189, 185, 184, 176, 175, 174, 170, 164,
       148, 145, 142, 125, 124, 122, 121, 121, 109, 104, 100,  96,  95,
        94,  92,  89,  74,  73,  64,  60,  55,  55,  54,  51,  44,  43,
        39,  37,  34,  33,  20,  16,  15,  12,  11,   7,   6])

In [9]:
int_numbers

array([  6,   7,  11,  12,  15,  16,  20,  33,  34,  37,  39,  43,  44,
        51,  54,  55,  55,  60,  64,  73,  74,  89,  92,  94,  95,  96,
       100, 104, 109, 121, 121, 122, 124, 125, 142, 145, 148, 164, 170,
       174, 175, 176, 184, 185, 189, 191, 191, 191, 194, 195])

In [10]:
# Selecionando os elementos de 2 em 2, começando do indice 5

int_numbers[5::2]

array([ 16,  33,  37,  43,  51,  55,  60,  73,  89,  94,  96, 104, 121,
       122, 125, 145, 164, 174, 176, 185, 191, 191, 195])

In [11]:
int_numbers

array([  6,   7,  11,  12,  15,  16,  20,  33,  34,  37,  39,  43,  44,
        51,  54,  55,  55,  60,  64,  73,  74,  89,  92,  94,  95,  96,
       100, 104, 109, 121, 121, 122, 124, 125, 142, 145, 148, 164, 170,
       174, 175, 176, 184, 185, 189, 191, 191, 191, 194, 195])

In [12]:
np.cumsum(int_numbers)

array([   6,   13,   24,   36,   51,   67,   87,  120,  154,  191,  230,
        273,  317,  368,  422,  477,  532,  592,  656,  729,  803,  892,
        984, 1078, 1173, 1269, 1369, 1473, 1582, 1703, 1824, 1946, 2070,
       2195, 2337, 2482, 2630, 2794, 2964, 3138, 3313, 3489, 3673, 3858,
       4047, 4238, 4429, 4620, 4814, 5009], dtype=int32)

In [13]:
# Mas para o que serve mesmo tudo isso?

# Vamos calcular a media movel de uma sequencia de precos

def media_movel(seu_array, n = 5):
    valores = np.cumsum(seu_array, dtype=float)
    valores[n:] = valores[n:] - valores[:-n]
    return valores[n - 1:] / n

In [ ]:
# Simulando um array de precos

precos = np.random.uniform(10,10000, size=100).round(2)

precos

In [ ]:
# Ajustando o array
precos.sort()

precos

In [ ]:
# Escolhendo o periodo da média movel

p = 8

In [ ]:
mm = media_movel(precos, n = p).round(2)

mm

In [ ]:
# Vamos ver no grafico

%matplotlib inline

import matplotlib.pyplot as plt


In [ ]:
plt.plot(precos, label = "Precos")
plt.plot(range(p ,p +len(mm)),mm, label = 'Media Movel')

In [ ]:
range(p ,p +len(mm))

In [ ]:
plt.plot(range(p ,p + len(mm)), mm, label = 'Media Movel')
plt.plot(precos, label = "Precos")
plt.title('Media Mòvel de 5 periodos da série simulada')
plt.xlabel("Periodo")
plt.ylabel("Preço");
plt.grid()
plt.legend()

In [ ]:
# Concatenando arrays

a1 = np.array([10, 20, 30, 40])
a2 = np.array([7, 8, 9, 10])
a3 = np.array([1, 2, 3, 4])

a4 = np.concatenate([a1, a3, a2])

a4

In [ ]:
# Concatenando arrays multidimensionais (as matrizes)

m1 = np.array([[10, 20], [30, 40]])
m2 = np.array([[7, 8], [9, 10]])
m3 = np.array([[1, 2], [3, 4]])

np.concatenate([m1, m2, m3])

In [ ]:
# E também fazer a concatenaçao por linha

np.concatenate([m1, m2, m3], axis = 1)

In [ ]:
# Adicionar e remover elementos

lista_produtos = np.array(["Notebook","Microfone","Game"])

lista_produtos

In [ ]:
# Append adiciona um novo item sempre no final do array

lista_produtos = np.append(lista_produtos, "Livro")

lista_produtos

In [ ]:
# Insert adiciona um novo item na posicao desejada

lista_produtos = np.insert(lista_produtos,1,"Celular")

lista_produtos

In [ ]:
# Remover um elemento

lista_produtos = np.delete(lista_produtos,[0]) 

lista_produtos