In [1]:
import numpy as np

In [8]:
n = np.random.randint(1, 100, size=20)
n

array([81, 29, 13,  5, 64, 53, 60, 62, 86, 10, 26, 43, 99, 48, 46, 29, 56,
       58, 47,  1])

In [9]:
v = np.cumsum(n)
v

array([ 81, 110, 123, 128, 192, 245, 305, 367, 453, 463, 489, 532, 631,
       679, 725, 754, 810, 868, 915, 916], dtype=int32)

In [10]:
v[5:]

array([245, 305, 367, 453, 463, 489, 532, 631, 679, 725, 754, 810, 868,
       915, 916], dtype=int32)

In [11]:
v[:-5]

array([ 81, 110, 123, 128, 192, 245, 305, 367, 453, 463, 489, 532, 631,
       679, 725], dtype=int32)

In [16]:
v[5:] = v[5:] - v[:-5]
v[5:]

array([   2,  -25,   -2,   69, -113,   -3,  -53, -101, -296,  -88,  -59,
         19,  -47,  109,  -62], dtype=int32)

In [18]:
v[5-1:]/5

array([ 38.4,   0.4,  -5. ,  -0.4,  13.8, -22.6,  -0.6, -10.6, -20.2,
       -59.2, -17.6, -11.8,   3.8,  -9.4,  21.8, -12.4])