In [1]:
#Sua primeira funcao

def soma_quadrados(a,b):
    return a*a + b*b

In [3]:
#Chamar a funcao

soma_quadrados(4,4)

32

In [4]:
#Atribuir a funcao em uma variavel

soma = soma_quadrados(3,4)

soma

25

In [8]:
#Uma funcao nao precisa ter necessariamente argumentos
import datetime

def dia_de_hoje():
    print("Hoje é " + str(datetime.datetime.now()))


In [9]:
dia_de_hoje()

Hoje é 2019-08-23 18:03:41.308822


In [10]:
#Ou pode ter argumento padrao e eu escolher se quero alterar ou nao

def dia_de_hoje(texto = "Hoje é "):
    print(texto + str(datetime.datetime.now()))

In [11]:
dia_de_hoje()

Hoje é 2019-08-23 18:04:35.031043


In [12]:
dia_de_hoje("No Brasil é ")

No Brasil é 2019-08-23 18:04:47.771548


In [14]:
# Vamos simplicar a vida com as funcoes - lembra da nossa sequencia de Fibonacci?
import numpy as np

n_elementos = 10

fibonacci = np.zeros(n_elementos)
fibonacci[1] = 1

for f in list(range(2, n_elementos)):
    fibonacci[f] = fibonacci[f-1] + fibonacci[f-2]
    
    
print(fibonacci)

[ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.]


In [15]:
#Transformando ela em funcao

def fibonacci(n_elementos):
    fibonacci = np.zeros(n_elementos)
    fibonacci[1] = 1
    for f in list(range(2, n_elementos)):
        fibonacci[f] = fibonacci[f-1] + fibonacci[f-2]
    print(fibonacci)

In [20]:
fibonacci(8)

[ 0.  1.  1.  2.  3.  5.  8. 13.]


In [21]:
# Sua rede neural em funcao

def minha_rna(inputs,outputs,interacoes):
    
    # Cria as matrizes de pesos da rede neural - w
    w1 = 2*np.random.random((inputs.shape[1], inputs.shape[0])) - 1
    w2 = 2*np.random.random((outputs.shape[0], outputs.shape[1])) - 1
    
    #Treinamento da rede
    for interacao in range(interacoes):
        camada1 = 1 / (1 + np.exp(-(np.dot(inputs,w1))))
        camada2 = 1 / (1 + np.exp(-(np.dot(camada1,w2))))
        camada2_delta = (outputs - camada2)*(camada2*(1-camada2))
        camada1_delta = camada2_delta.dot(w2.T) * (camada1 * (1-camada1))
        w2 += camada1.T.dot(camada2_delta)
        w1 += inputs.T.dot(camada1_delta)
        
    print(camada2.round())

In [22]:
# Cria as matrizes de entrada e saida. Neste caso, é a tabela verdade da funçao logica AND (E)

entradas = np.array([ [0,0],[0,1],[1,0],[1,1] ])
saidas = np.array([[0,0,0,1]]).T

In [23]:
#Chamando a funcao

minha_rna(entradas,saidas,1000)

[[0.]
 [0.]
 [0.]
 [1.]]


In [24]:
#Vamos treinar a rede para funcao OR

entradas_or = np.array([ [0,0],[0,1],[1,0],[1,1] ])
saidas_or = np.array([[0,1,1,1]]).T

In [25]:
minha_rna(entradas_or,saidas_or,1000)

[[0.]
 [1.]
 [1.]
 [1.]]


In [26]:
#Vamos treinar a rede para funcao XOR

saidas_xor = np.array([[0,1,1,0]]).T

In [27]:
saidas_xor

array([[0],
       [1],
       [1],
       [0]])

In [29]:
minha_rna(entradas,saidas_xor,1000)

[[0.]
 [1.]
 [1.]
 [0.]]
