In [2]:
import numpy as np

In [3]:
n = np.random.randint(1, 100, size=20)
n

array([ 8, 10, 46,  4, 10, 98, 49, 91, 81, 16, 11, 67, 82, 24, 37, 59, 82,
       72, 21, 69])

In [4]:
v = np.cumsum(n)
v

array([  8,  18,  64,  68,  78, 176, 225, 316, 397, 413, 424, 491, 573,
       597, 634, 693, 775, 847, 868, 937], dtype=int32)

In [5]:
v[5:]

array([176, 225, 316, 397, 413, 424, 491, 573, 597, 634, 693, 775, 847,
       868, 937], dtype=int32)

In [6]:
v[:-5]

array([  8,  18,  64,  68,  78, 176, 225, 316, 397, 413, 424, 491, 573,
       597, 634], dtype=int32)

In [7]:
v[5:] = v[5:] - v[:-5]
v[5:]

array([168, 207, 252, 329, 335, 248, 266, 257, 200, 221, 269, 284, 274,
       271, 303], dtype=int32)

In [8]:
v[5-1:]/5

array([15.6, 33.6, 41.4, 50.4, 65.8, 67. , 49.6, 53.2, 51.4, 40. , 44.2,
       53.8, 56.8, 54.8, 54.2, 60.6])

In [10]:
np.random.uniform(1, 10, size=5)

array([7.50748567, 9.2453604 , 5.49499449, 4.2471987 , 4.81969581])