In [7]:
m1 = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
m1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
m1[0]

[1, 2, 3]

In [11]:
m1[1][0]

4

In [12]:
import numpy as np

In [13]:
m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(m2)

numpy.ndarray

In [16]:
m2[0]

array([1, 2, 3])

In [17]:
m2[1]

array([4, 5, 6])

In [18]:
m2[2, 2]

9

In [19]:
m2[:, 1]

array([2, 5, 8])

In [20]:
m2.shape

(3, 3)

In [28]:
for i in range(0, m2.shape[0]):
    for j in range(0, m2.shape[1]):
        print(m2[i, j])


1
2
3
4
5
6
7
8
9


In [27]:
m2[0, 0]

1